"""add camera table

Revision ID: 2026031001
Revises: e22c41b0d69a
Create Date: 2026-03-10 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026031001'
down_revision: Union[str, None] = 'e22c41b0d69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
                    sa.Column('uuid', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('location', sa.String(
                        length=200), nullable=False),
                    sa.Column('rtsp_url', sa.String(
                        length=500), nullable=False),
                    sa.Column('stream_path', sa.String(
                        length=100), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('uuid', name=op.f('camera_pkey')),
                    sa.UniqueConstraint(
                        'stream_path', name=op.f('camera_stream_path_key'))
                    )
    op.create_index(op.f('ix_camera_is_deleted'),
                    'camera', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_camera_stream_path'),
                    'camera', ['stream_path'], unique=False)
    op.create_index(op.f('ix_camera_uuid'), 'camera', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_uuid'), table_name='camera')
    op.drop_index(op.f('ix_camera_stream_path'), table_name='camera')
    op.drop_index(op.f('ix_camera_is_deleted'), table_name='camera')
    op.drop_table('camera')
    # ### end Alembic commands ###
