"""add created_by and updated_by to customer_contact

Revision ID: 4a092a45c201
Revises: 128280217923
Create Date: 2025-11-07 05:50:05.289952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a092a45c201'
down_revision: Union[str, None] = '128280217923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'),
                  table_name='token_blacklist')
    op.drop_table('token_blacklist')

    # Add columns as nullable first
    op.add_column('customer_contact', sa.Column(
        'created_by', sa.String(length=100), nullable=True))
    op.add_column('customer_contact', sa.Column(
        'updated_by', sa.String(length=100), nullable=True))

    # Update existing rows with a default value
    op.execute(
        "UPDATE customer_contact SET created_by = 'system' WHERE created_by IS NULL")
    op.execute(
        "UPDATE customer_contact SET updated_by = 'system' WHERE updated_by IS NULL")

    # Now make created_by NOT NULL
    op.alter_column('customer_contact', 'created_by', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_contact', 'updated_by')
    op.drop_column('customer_contact', 'created_by')
    op.create_table('token_blacklist',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('token', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('expires_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('token_blacklist_pkey'))
                    )
    op.create_index(op.f('ix_token_blacklist_token'),
                    'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
