"""add deleted status to customer account_status constraint

Revision ID: 8e2774e70911
Revises: 4a092a45c201
Create Date: 2025-11-07 11:02:27.599028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e2774e70911'
down_revision: Union[str, None] = '4a092a45c201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'),
                  table_name='token_blacklist')
    op.drop_table('token_blacklist')

    # Drop old constraint and add new one with 'Deleted' status
    op.drop_constraint('chk_account_status_values', 'customer', type_='check')
    op.create_check_constraint(
        'chk_account_status_values',
        'customer',
        "account_status IN ('Active', 'Inactive', 'Suspended', 'Pending', 'Deleted')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert to old constraint without 'Deleted' status
    op.drop_constraint('chk_account_status_values', 'customer', type_='check')
    op.create_check_constraint(
        'chk_account_status_values',
        'customer',
        "account_status IN ('Active', 'Inactive', 'Suspended', 'Pending')"
    )

    op.create_table('token_blacklist',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('token', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('expires_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('token_blacklist_pkey'))
                    )
    op.create_index(op.f('ix_token_blacklist_token'),
                    'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
