"""add_zone_model_and_fk_to_camera_user

Revision ID: b613c62ee7f1
Revises: 2026031101
Create Date: 2026-04-07 05:56:33.514583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b613c62ee7f1'
down_revision: Union[str, None] = '2026031101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.add_column('camera', sa.Column('zone_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_camera_zone_id'), 'camera', ['zone_id'], unique=False)
    op.create_unique_constraint(None, 'camera', ['uuid'])
    op.create_foreign_key(None, 'camera', 'zone', ['zone_id'], ['uuid'], ondelete='SET NULL')
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('rank', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('zone_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_zone_id'), 'user', ['zone_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['uuid'])
    op.create_foreign_key(None, 'user', 'zone', ['zone_id'], ['uuid'], ondelete='SET NULL')
    op.drop_column('user', 'zone')
    op.create_unique_constraint(None, 'zone', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zone', type_='unique')
    op.add_column('user', sa.Column('zone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_zone_id'), table_name='user')
    op.drop_column('user', 'zone_id')
    op.drop_column('user', 'rank')
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'camera', type_='foreignkey')
    op.drop_constraint(None, 'camera', type_='unique')
    op.drop_index(op.f('ix_camera_zone_id'), table_name='camera')
    op.drop_column('camera', 'zone_id')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
